[package]
name = "zktree"
version = "0.1.0"
authors = ["Alireza Meskin <alireza.meskin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zookeeper = "0.5.9"
clap = "~2.27.0"
